name: Update TikTok Stats

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Init Project & Install node-fetch
        run: |
          npm init -y
          npm install node-fetch@2

      - name: Run Update Script
        run: node update-stats.js

      - name: Commit dan Push Perubahan
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add database/stats.json
          git commit -m "chore: update TikTok stats [CI]" || echo "⚠️ No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

